# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
