# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categories',
        ),
    ]
