# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20170710_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
