# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_technology_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='what_i_learned',
            field=models.TextField(blank=True),
        ),
    ]
