# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_what_i_learned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='link',
        ),
    ]
